# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jitensha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AlamofireObjectMapper'
  pod 'TPKeyboardAvoiding'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Stripe'

  # Pods for jitensha

  target 'jitenshaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jitenshaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
